//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("EN5Player")]
[assembly: System.Reflection.AssemblyDescription("EN5Player for EasiNote5")]
[assembly: System.Reflection.AssemblyProduct("EN5Player")]
[assembly: System.Reflection.AssemblyCopyright("All Copyright (c) 2017 Iron.")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.0.6")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.6")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.6")]


